"""Add rejection_reason to Appeal model

Revision ID: 04d60a2cde43
Revises: 1c6e9b85f901
Create Date: 2025-05-07 12:32:28.684043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d60a2cde43'
down_revision = '1c6e9b85f901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True, comment="申诉驳回原因，仅在status='rejected'时有值"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
