"""add score tables

Revision ID: 0d8c25993727
Revises: 5ee067cc2aa1
Create Date: 2025-05-06 12:55:47.843685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8c25993727'
down_revision = '5ee067cc2aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_rules',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键，自增'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='事件类型标识，如 forbidden_parking、normal_parking 等'),
    sa.Column('points', sa.Integer(), nullable=False, comment='该事件对应的加减分值，正数代表加分，负数代表扣分'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='规则文字描述'),
    sa.Column('frequency_limit', sa.String(length=255), nullable=True, comment='频率与上限说明，比如“每次扣10，日累计上限-30”'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注，例如“超3次通报”'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type')
    )
    op.create_table('appeals',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='申诉主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申诉用户 ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='相关车辆 ID，可选'),
    sa.Column('license_plate', sa.String(length=32), nullable=True, comment='相关车牌号'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='被申诉的事件类型'),
    sa.Column('reason', sa.Text(), nullable=False, comment='申诉理由'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='appeal_status'), nullable=False, comment='申诉状态：pending 待审；approved 同意；rejected 驳回'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='申诉提交时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appeals_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeals_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('reported_events',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='上报记录主键'),
    sa.Column('reporter_id', sa.Integer(), nullable=False, comment='上报人用户 ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='相关车辆 ID，可选'),
    sa.Column('license_plate', sa.String(length=32), nullable=True, comment='相关车牌号'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='上报的事件类型'),
    sa.Column('details', sa.Text(), nullable=True, comment='上报详情，如图片地址或文字说明'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='report_status'), nullable=False, comment='审核状态：pending 待审；approved 通过；rejected 驳回'),
    sa.Column('adjust_points', sa.Integer(), nullable=False, comment='管理员审核时自定义的加减分值'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='上报时间'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reported_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reported_events_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reported_events_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('score_logs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='日志主键，自增'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户 ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='关联的车辆 ID（可选），车辆删除后设为 NULL'),
    sa.Column('license_plate', sa.String(length=32), nullable=True, comment='当时的车牌号冗余存储'),
    sa.Column('event_type', sa.String(length=64), nullable=True, comment='触发的事件类型，对应 ScoreRule.event_type'),
    sa.Column('points', sa.Integer(), nullable=False, comment='本次变动的分值'),
    sa.Column('source', sa.Enum('auto', 'manual', 'report', 'appeal', name='score_source'), nullable=False, comment='来源：auto 系统自动；manual 手动调整；report 上报审核；appeal 申诉处理'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_logs_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_logs_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_score_logs_user_id'))

    op.drop_table('score_logs')
    with op.batch_alter_table('reported_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reported_events_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_reported_events_reporter_id'))

    op.drop_table('reported_events')
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeals_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_appeals_user_id'))

    op.drop_table('appeals')
    op.drop_table('score_rules')
    # ### end Alembic commands ###
