"""Add slot_time and created_at to charging_sessions

Revision ID: 0ecfa49414d1
Revises: 55f0737287a7
Create Date: 2025-04-23 14:48:13.275034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ecfa49414d1'
down_revision = '55f0737287a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_piles', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_charging_piles_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_piles_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('uix_location_pile_name', ['location_id', 'name'])
        batch_op.drop_constraint('charging_piles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campus_locations', ['location_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.alter_column('slot_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_charging_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_sessions_pile_id'), ['pile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_sessions_slot_time'), ['slot_time'], unique=False)
        batch_op.create_index('ix_session_status', ['status'], unique=False)
        batch_op.create_index('ix_session_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uix_pile_slot', ['pile_id', 'slot_time'])
        batch_op.drop_constraint('charging_sessions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('charging_sessions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'charging_piles', ['pile_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'electric_vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('charging_sessions_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('charging_sessions_ibfk_1', 'charging_piles', ['pile_id'], ['id'])
        batch_op.drop_constraint('uix_pile_slot', type_='unique')
        batch_op.drop_index('ix_session_user')
        batch_op.drop_index('ix_session_status')
        batch_op.drop_index(batch_op.f('ix_charging_sessions_slot_time'))
        batch_op.drop_index(batch_op.f('ix_charging_sessions_pile_id'))
        batch_op.drop_index(batch_op.f('ix_charging_sessions_created_at'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('slot_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('charging_piles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('charging_piles_ibfk_1', 'campus_locations', ['location_id'], ['id'])
        batch_op.drop_constraint('uix_location_pile_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_charging_piles_status'))
        batch_op.drop_index(batch_op.f('ix_charging_piles_location_id'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
