"""Add CampusLocation model

Revision ID: 13b48af392b3
Revises: 69bb2dcd19e4
Create Date: 2025-03-25 16:02:21.693774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b48af392b3'
down_revision = '69bb2dcd19e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False, comment='类型：parking（停车场）、charging（充电桩）、building（教学楼）、dining（食堂）等'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campus_locations')
    # ### end Alembic commands ###
