"""增加申诉记录关联

Revision ID: 1c6e9b85f901
Revises: 558f39e654e5
Create Date: 2025-05-07 12:14:00.455212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6e9b85f901'
down_revision = '558f39e654e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_log_id', sa.BigInteger(), nullable=False, comment='申诉的扣分记录ID'))
        batch_op.create_index(batch_op.f('ix_appeals_score_log_id'), ['score_log_id'], unique=False)
        batch_op.create_foreign_key(None, 'score_logs', ['score_log_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appeals_score_log_id'))
        batch_op.drop_column('score_log_id')

    # ### end Alembic commands ###
