"""delete license_plate

Revision ID: 1cd93568dcf6
Revises: 65c9abc5eb64
Create Date: 2025-03-21 10:41:48.419394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cd93568dcf6'
down_revision = '65c9abc5eb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('license_plate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_plate', mysql.VARCHAR(length=15), nullable=True))

    # ### end Alembic commands ###
