"""add violations table

Revision ID: 251cd54aed0b
Revises: 0d8c25993727
Create Date: 2025-05-06 13:40:01.548911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251cd54aed0b'
down_revision = '0d8c25993727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='违规记录主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='违规用户 ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='相关车辆 ID，可选'),
    sa.Column('license_plate', sa.String(length=32), nullable=True, comment='车牌号冗余'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='事件类型，如 forbidden_parking、other_violation'),
    sa.Column('location', sa.String(length=128), nullable=True, comment='违规发生地点'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='违规发生时间'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='violation_status'), nullable=False, comment='审核状态：pending 待审；approved 通过；rejected 驳回'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_violations_user_id'))

    op.drop_table('violations')
    # ### end Alembic commands ###
