"""修改model列

Revision ID: 313b0993d619
Revises: 766a1e93397e
Create Date: 2025-04-09 16:57:54.572780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '313b0993d619'
down_revision = '766a1e93397e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_vehicles', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_comment='车辆型号')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_vehicles', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_comment='车辆型号')

    # ### end Alembic commands ###
