"""Add path field to CampusLocation

Revision ID: 34816741a333
Revises: d824b2a494e7
Create Date: 2025-04-17 19:37:11.857395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34816741a333'
down_revision = 'd824b2a494e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_locations', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.JSON(),
               nullable=False,
               existing_comment='区域路径（多边形顶点坐标）')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_locations', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.JSON(),
               nullable=True,
               existing_comment='区域路径（多边形顶点坐标）')

    # ### end Alembic commands ###
