"""增加分数字段

Revision ID: 558f39e654e5
Revises: 251cd54aed0b
Create Date: 2025-05-06 17:33:32.457371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558f39e654e5'
down_revision = '251cd54aed0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False, comment='当前积分（缓存所有 ScoreLog 的累加）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
