"""Add Camera and Violation tables

Revision ID: 5ee067cc2aa1
Revises: 55f0737287a7
Create Date: 2025-05-05 09:55:14.357066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee067cc2aa1'
down_revision = '55f0737287a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rtsp_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['campus_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_pile_slot', ['pile_id', 'slot_time'])
        batch_op.drop_constraint('charging_sessions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('charging_sessions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'charging_piles', ['pile_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'electric_vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('charging_sessions_ibfk_1', 'charging_piles', ['pile_id'], ['id'])
        batch_op.create_foreign_key('charging_sessions_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uix_pile_slot', type_='unique')

    op.drop_table('violation')
    op.drop_table('camera')
    # ### end Alembic commands ###
