"""Add ElectricVehicle model

Revision ID: 65c9abc5eb64
Revises: b30361ace307
Create Date: 2025-03-17 21:04:38.077405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c9abc5eb64'
down_revision = 'b30361ace307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electric_vehicles',
    sa.Column('id', sa.Integer(), nullable=False, comment='电动车ID'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='车辆所有者ID'),
    sa.Column('brand', sa.String(length=50), nullable=False, comment='车辆品牌'),
    sa.Column('model', sa.String(length=50), nullable=False, comment='车辆型号'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='车辆颜色'),
    sa.Column('plate_number', sa.String(length=15), nullable=False, comment='车牌号'),
    sa.Column('battery_capacity', sa.Integer(), nullable=True, comment='电池容量（单位：Wh）'),
    sa.Column('registered_at', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='车辆状态'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electric_vehicles')
    # ### end Alembic commands ###
