"""delete permission_expire

Revision ID: 69bb2dcd19e4
Revises: be530259d3d9
Create Date: 2025-03-22 10:05:36.290126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bb2dcd19e4'
down_revision = 'be530259d3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('permission_expire')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_expire', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
