"""Add parking lot and parking space models

Revision ID: 766a1e93397e
Revises: 13b48af392b3
Create Date: 2025-04-01 14:47:30.809810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766a1e93397e'
down_revision = '13b48af392b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False, comment='停车场ID'),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='停车场名称'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='停车场总容量'),
    sa.Column('occupied', sa.Integer(), nullable=False, comment='已占用车位数'),
    sa.ForeignKeyConstraint(['location_id'], ['campus_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_spaces',
    sa.Column('id', sa.Integer(), nullable=False, comment='停车位ID'),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False, comment='停车位状态'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='停车记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('parking_space_id', sa.Integer(), nullable=False),
    sa.Column('park_in_time', sa.DateTime(), nullable=True, comment='停车时间'),
    sa.Column('park_out_time', sa.DateTime(), nullable=True, comment='出库时间'),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_records')
    op.drop_table('parking_spaces')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
