"""增加车辆图片URl

Revision ID: ca3fab59e477
Revises: 313b0993d619
Create Date: 2025-04-14 13:28:02.416778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3fab59e477'
down_revision = '313b0993d619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_vehicles', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
