"""Add path field to CampusLocation

Revision ID: d824b2a494e7
Revises: ca3fab59e477
Create Date: 2025-04-17 19:35:30.549535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd824b2a494e7'
down_revision = 'ca3fab59e477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.JSON(), nullable=True, comment='区域路径（多边形顶点坐标）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_locations', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
